---
title: "Testings"
author: "Michael Helton"
date: "12/7/2021"
output: html_document
---
```{r}
# Load packages
library(bayesrules)
library(tidyverse)
library(rstanarm)
library(broom.mixed)
library(tidybayes)
library(forcats)
library(bayesplot)
library(lubridate)
library(nflfastR)
```


```{r}
modelpre <- readRDS('pregame_model.rds')
model1st <- readRDS('first_quarter.rds')
model2nd <- readRDS('second_quarter.rds')
model3rd <- readRDS("third_quarter.rds")
```

```{r}
tidy(modelpre)
```


```{r}
model <- readRDS("quarter_model.rds")
```

```{r}
plot_normal(0, 2.5)
```


```{r}
prior_summary(model)
```


```{r}
predictions <- posterior_predict(model, newdata = data.frame(score_differential.x = 0, 
                                                             score_differential.y = 3, 
                                                             score_differential.x.x = 10)) %>%
  as.data.frame(.) %>%
  summarise(Prob = mean(`1`))
```

```{r}
predictions %>%
  summarise(Prob = mean(`1`))
```


```{r}
df_p <- data.frame(preds = seq(-21, 21, by = 1))
df_p <- df_p %>%
  mutate(names = 'Pregame',
         game = 'game')

df_1 <- data.frame(preds = seq(-30, 30, by = 1))
df_1 <- df_1 %>%
  mutate(names = 'Quarter 1',
         game = 'game')

df_2 <- data.frame(preds = seq(-30, 30, by = 1))
df_2 <- df_2 %>%
  mutate(names = 'Quarter 2',
         game = 'game')

df_3 <- data.frame(preds = seq(-30, 30, by = 1))
df_3 <- df_3 %>%
  mutate(names = 'Quarter 3',
         game = 'game')

df <- df_p %>%
  rbind(df_1, df_2, df_3)
```

```{r}
write.csv(df, file = 'df.csv')
```

```{r}
df %>%
  filter(preds_pre == .01, 
         preds_1 == .02,
         preds_2 == .03,
         preds_3 == .04)
```







